# Generated by Django 5.0.2 on 2024-04-19 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commander",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Commander name"),
                ),
                ("year", models.IntegerField(verbose_name="Commander year")),
                ("did", models.CharField(max_length=255, verbose_name="Commander did")),
                (
                    "area",
                    models.CharField(max_length=255, verbose_name="Commander area"),
                ),
                ("image", models.ImageField(upload_to="commander/")),
                (
                    "commander_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commander list",
                "db_table": "commander",
            },
        ),
    ]
